[all:children]
azure-vm

[azure-vm]
vm-az-kr-mgmt-netbox-01 ansible_host=10.1.0.4 ansible_port=22 ansible_connection=ssh ansible_user=azureuser ansible_password='Qwer1234!@#$'
vm-az-kr-mgmt-ansible-01 ansible_host=10.1.0.6 ansible_port=22 ansible_connection=ssh ansible_user=azureuser ansible_password='Qwer1234!@#$'