- name: Find result directories
  ansible.builtin.find:
    paths:
      - "/root"
      - "/home"
    file_type: directory
    patterns: "LINUX*"
    recurse: yes
  register: result_dirs

- name: Show result directories
  ansible.builtin.debug:
    var: result_dirs.files