- name: Create work directory
  file:
    path: /tmp/vuln_check
    state: directory
    mode: '0755'

- name: Upload vulnerability script
  copy:
    src: LINUX_2026.sh
    dest: /tmp/vuln_check/LINUX_2026.sh
    mode: '0755'