- name: Create work directory
  ansible.builtin.file:
    path: /tmp/vuln_check
    state: directory
    mode: '0777'

- name: Run vulnerability check
  shell: |
    export Running_WebService=0
    echo "1" | /tmp/vuln_check/LINUX_2026.sh
  args:
    executable: /bin/bash
  register: vuln_result
  ignore_errors: yes