- name: Compress result directory
  community.general.archive: 
    path: "{{ item.path }}"
    dest: "/tmp/{{ inventory_hostname }}.tar.gz"
    format: gz
  loop: "{{ result_dirs.files }}" 

- name: Fetch archive to AWX
  fetch:
    src: "/tmp/{{ inventory_hostname }}.tar.gz"
    dest: "./result/"
  flat: yes

- name: Upload archive to Nexus
  ansible.builtin.shell: |
    curl -k -u "{{ nexus_user }}:{{ nexus_password }}" \
    --upload-file "./result/{{ inventory_hostname }}.tar.gz" \
    "{{ nexus_url }}/{{ nexus_repository }}/{{ inventory_hostname }}/{{ inventory_hostname }}.tar.gz"
  delegate_to: localhost 